name: Android Tests & Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit and Instrumentation Tests
    runs-on: ubuntu-latest

    strategy:
      matrix:
        api-level: [29]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission to Gradle
        run: chmod +x gradlew

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        
      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Run tests and generate coverage
        uses: reactivecircus/android-emulator-runner@v2
        with:
          avd-name: default_android_emulator
          api-level: ${{ matrix.api-level }}
          target: google_apis
          arch: x86_64
          profile: pixel_3a
          script: |
            adb -e wait-for-device
            adb -e shell settings put global window_animation_scale 0.0
            adb -e shell settings put global transition_animation_scale 0.0
            adb -e shell settings put global animator_duration_scale 0.0
            ./gradlew jacocoTestReport
        env:
          ANDROID_EMULATOR_DEBUG: "true"
          ANDROID_EMULATOR_WAIT_TIME_BEFORE_KILL: 60

      - name: Find Coverage Files
        run: |
          echo "Finding coverage files..."
          COVERAGE_FILE_1=$(find ${{ github.workspace }}/flizpaysdk -type f -name "coverage.ec" | head -n 1)
          COVERAGE_FILE_2=$(find ${{ github.workspace }}/flizpaysdk -type f -name "testDebugUnitTest.exec" | head -n 1)
          echo "Coverage files found:"
          echo $COVERAGE_FILE_1
          echo $COVERAGE_FILE_2
          
          echo "COVERAGE_FILE_1=$COVERAGE_FILE_1" >> $GITHUB_ENV
          echo "COVERAGE_FILE_2=$COVERAGE_FILE_2" >> $GITHUB_ENV


      - name: Upload to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-empty: true
          debug: true
          measure: true
          files: $COVERAGE_FILE_1 $COVERAGE_FILE_2

      - name: Upload Test Reports (for debugging)
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: test-reports
          path: app/build/reports/tests

      - name: Force Kill Emulator After Tests
        run: |
          adb -s emulator-5554 emu kill || true
          adb -e kill-server || true
          kill $(pgrep -f emulator) || true
